; Optional PlatformIO support.
; Arduino IDE users can ignore this file.

[platformio]
src_dir = .

[env:esp32s3]
platform = espressif32 @ 6.13.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<*.cpp>
    +<*.ino>
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    adafruit/Adafruit NeoPixel @ 1.12.3
